language: objective-c
osx_image: xcode10.1
cache:
  directories:
  - Carthage
before_install:
  - brew install carthage
  - brew install swiftgen
  - brew install swiftlint
  - gem install xcpretty
  - gem install xcpretty-travis-formatter
  - gem install fastlane -NV
script:
  - fastlane carthage_bootstrap  
  - fastlane tests
notifications:
  email:
    on_success: never
after_success:
  - fastlane test_coverage