language: objective-c
osx_image: xcode9.4
cache:
  directories:
  - Carthage
before_install:
  - brew install carthage
  - brew install swiftgen
  - carthage bootstrap --platform iOS --cache-builds  
  - gem install xcpretty
  - gem install xcpretty-travis-formatter
  - gem install fastlane -NV
script:
  - fastlane tests
notifications:
  email:
    on_success: never
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'iOSSampleApp'
