language: objective-c
osx_image: xcode10.1
cache:
  directories:
  - Carthage
before_install:
  - brew update
  - brew ls --versions carthage && brew upgrade carthage || brew install carthage
  - brew ls --versions swiftgen && brew upgrade swiftgen || brew install swiftgen
  - brew ls --versions swiftlint && brew upgrade swiftlint || brew install swiftlint    
  - gem install xcpretty
  - gem install xcpretty-travis-formatter
  - gem install fastlane -NV
script:
  - fastlane carthage_bootstrap  
  - fastlane tests
notifications:
  email:
    on_success: never
after_success:
  - fastlane test_coverage