name: Test

on: [push]
env:
  DEVELOPER_DIR: /Applications/Xcode_15.0.1.app/Contents/Developer

jobs:
  job-test:
    name: Run unit tests
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v1

    - name: Install needed software
      run: |
        gem install xcpretty
        gem install bundler:1.17.2

    - name: Run unit tests
      run: fastlane tests